### ISSUE TITLE
character entities not working

### ISSUE THREAD

**Issue by Madd4Computers** [jonkemp/inline-css#34] opened 2016-03-23 19:24 UTC
I use a lot of **&amp;nbsp;** and since the Inliner change, they aren't replaced correctly. I get the following instead so I end up seeing the code for what it is in my result and see this ( **&amp;amp;nbsp;** ) in my code.

**Comment by tlhaynes** [comment] 2016-03-23 20:06
noticing it happening with a few other character entities as well, including `&lt;` and `&gt;`

**Comment by tjtate** [comment] 2016-03-23 20:14
same here!

**Comment by jonkemp** [comment] 2016-03-24 00:32
Could you provide a failing test?

**Comment by questexasia** [comment] 2016-03-24 07:55
Face same problem here.
Some example code is:
`Original code: <p>Dear &lt;insert name&gt;,<insert name=""></insert></p>`
`After inlined: <p style="margin:0 0 12px 0;margin-bottom:12px">Dear &amp;lt;insert name&amp;gt;,<insert name=""></insert></p>`

**Comment by genied** [comment] 2016-03-24 09:51
Same for me, I have to replace every &amp;nbsp; back to &nbsp;

**Comment by rmullowney** [comment] 2016-03-24 16:19
&amp; is converted to &amp;amp; as well

**Comment by jonkemp** [comment] 2016-03-24 17:11
Interesting that so many are experiencing this now when these changes were released almost a month ago. I will look at it. Thanks for the report.

**Comment by tjtate** [comment] 2016-03-24 17:24
Its worth noting that zurb is pointing to this page from there online inliner tool, which they just changed: http://foundation.zurb.com/emails/inliner.html

**Comment by jonkemp** [comment] 2016-03-24 17:46
Ah, I see. If you are seeing this issue then, 2.1.0 is the version you should use until a fix is made.

**Comment by tjtate** [comment] 2016-03-24 18:02
@tdhartwick not sure if your the guy but pulling you in for zurb inliner tool to be fixed.

**Comment by jonkemp** [comment] 2016-03-25 03:10
I just added a test for this case and it passes. 4b59946

So, I'm confused as to how this is happening. Please post your code samples and make sure you are using the latest version.

**Comment by jonkemp** [comment] 2016-03-25 03:50
I also have an issue with the Zurb Inliner page linking to this issue tracker. There must be other things touching the output besides just this package. inline-css does not add the xhtml doctype or namespace and also does not minify the html. Something else is doing that. Is that code open sourced somewhere? How can I provide support for their issues if I can't see how the module is being used?

 I ran the same test using the inliner and it passed as well FWIW.

**Comment by liperry** [comment] 2016-03-25 12:23
I believe I am using the latest version 2.2.2 and starting 2 days ago, the inliner is totally wrecking my code. Same issues as those above... &nbsp; converting to &amp;nbsp; as well as &amp; converting to &amp;amp;   

Do you any idea when this will be resolved? and if I need to use version 2.1.0 in the meantime, how do I get to that version?  Thanks!!

**Comment by liperry** [comment] 2016-03-25 13:17
So.... I just put all of my code in the HTML box on the inliner page and put my CSS in there as well as I used to in the old version. I did NOT use the CSS box below and it WORKED!!  Seems that putting my css files in the second box was causin it to not be in the correct order.

**Comment by jonkemp** [comment] 2016-03-25 14:30
@liperry I do not have an idea when this will be resolved. I can't reproduce the issue actually from within this module. I added a test to try to reproduce it and the test passes. 

I will need to see some kind of code sample to be able to debug the issue and nobody has given me one yet. 

_This is not support for Responsive Email Inliner. This is issue tracking for the inline-css module._ Zurb's software uses my module, but I have suspicion its not the only module being used. But I don't know because I don't have access to their software. Zurb needs to support their own products, and if they find the issue is with this module, then they need to create an issue here instead of directing the users to file an issue here.

I'm very close to closing this issue. However, I'm willing to allow some more time for someone to post code samples.

**Comment by Madd4Computers** [comment] 2016-03-25 16:04
I haven't had access to my computer for the last couple days so have been unable to contribute to this issue. I attached the file I'm using and inserting into the inliner tool. Let me know if this helps and maybe with my exact file you can replicate the issue...? [appDev_template.zip](https://github.com/jonkemp/inline-css/files/189693/appDev_template.zip)

What do you mean by different versions? Of the tool?

**Comment by jonkemp** [comment] 2016-03-25 16:47
@Madd4Computers versions of the inline-css module which is a module for node.js. I'll restate here what I stated above, _this is not support for Responsive Email Inliner. This is issue tracking for the inline-css module._ Thanks for posting your files. I'll look at it when I get a chance, but I develop the inline-css module for node.js. I do not work for Zurb and do not have access to their codebase, so I cannot troubleshoot issues with their tool.

**Comment by tjtate** [comment] 2016-03-25 17:03
Ive opened up a forum on zurbs site here to comment: 

http://foundation.zurb.com/forum/posts/39134-problems-with-your-inliner-tool

**Comment by Madd4Computers** [comment] 2016-03-25 19:02
@jonkemp Thanks for clearing that up and @tjtate, thanks for creating a new forum post on Zurb's site for this issue.

**Comment by jonkemp** [comment] 2016-03-28 20:00
Looks like this is the project on GitHub. You might try filing an issue there.

https://github.com/zurb/foundation-emails

**Comment by gakimball** [comment] 2016-03-30 17:32
@jonkemp We'll take down the link to inline-css on our web inliner. You're right, there are enough extra things we have to do to get the HTML email-ready that it's not always going to be inline-css's issue.

**Comment by jonkemp** [comment] 2016-03-30 17:35
Closing for now. I'm willing to reopen this if someone has code samples or a failing test.

**Closed by jonkemp** 2016-03-30 17:35 UTC
