### ISSUE TITLE
Inline Conversion

### ISSUE THREAD

**Issue by Ankiewicz** [jonkemp/inline-css#35] opened 2016-03-25 22:56 UTC
Up inlining - your inliner is turning all of my '&" into the html element '&amp;' So now any url's and non breaking spaces are now `'&amp;amp;nbsp;`'

**Comment by jonkemp** [comment] 2016-03-26 00:10
Closing because it is a duplicate of #34. However, I will state this again here. This is a repo for an node.js module, not a support site for Zurb's Responsive Email Inliner tool. I don't work for Zurb or support their code, so please file an issue with them.

**Comment by Ankiewicz** [comment] 2016-03-26 00:11
Their inline page links to your repo...

**Closed by jonkemp** 2016-03-26 00:10 UTC
Labels: duplicate
