### ISSUE TITLE
Preserve media queries inside external CSS

### ISSUE THREAD

**Issue by gakimball** [jonkemp/inline-css#30] opened 2016-03-07 18:29 UTC
Right now, the `preserveMediaQueries` option only applies to CSS inside of a document's `<style>` tag, not to external CSS resolved via `<link>` tags.

Allowing media queries inside external CSS to be transferred to the `<style>` tag would allow for a much simpler workflow, assuming you're using a library like [Ink](https://github.com/zurb/foundation-emails), or any CSS library for writing HTML emails.

**Comment by jonkemp** [comment] 2016-03-07 20:33
Duplicate of #26.

**Closed by jonkemp** 2016-03-07 20:33 UTC
