### ISSUE TITLE
should not remove spaces in calc() function

### ISSUE THREAD

**Issue by adekbadek** [jonkemp/inline-css#57] opened 2016-12-13 13:12 UTC
Spaces are mandatory inside CSS [`calc()`](https://developer.mozilla.org/en/docs/Web/CSS/calc) function, and should not be removed in inlining.

To reproduce: 

```javascript
const inlineCss = require('inline-css');
const html = `
  <style>
    div{width: calc(100% - 20px);}
  </style>
  <div/>
`;

inlineCss(html, {url: '/'}).then(function(html) { console.log(html); });
// => <div style="width: calc(100%-20px);"></div>
```

**Comment by jonkemp** [comment] 2016-12-15 16:01
Related: https://github.com/jonkemp/gulp-inline-css/issues/37

**Comment by jonkemp** [comment] 2017-01-18 15:34
The issue is in this module:

https://github.com/NV/CSSOM

I've created an issue for this here.

https://github.com/NV/CSSOM/issues/86

**Comment by jonkemp** [comment] 2017-01-20 19:14
The issue in CCSOM was fixed so it should be available in their next release.

**Comment by jonkemp** [comment] 2017-01-26 03:06
I'm closing this as it's been resolved in the latest release of the cssom module. If you update your dependencies, it should work. If it's not working, make sure you have cssom 0.3.2.

**Closed by jonkemp** 2017-01-26 03:06 UTC
